export const facts = [
  "There are 63 million pairs of chopsticks — or 126 million single sticks — manufactured in China every year. These range from mass-produced disposable chopsticks to high-quality sticks that can take up to (yes) a month to painstakingly make.",
  "India gave the world its sweet tooth. Although sugarcane originated in Southeast Asia, it was first chemically refined about 2,500 years ago in India. (Thanks, India!)",
  "The stars and stripes in the United states of America's flag make up one of the most recognizable flags of any country in the world. But did you know the modern iteration containing 50 stars was designed for a class project by an enterprising high school student in 1958, who anticipated the addition of Alaska and Hawaii a year later? Amazingly, the boy's unimpressed teacher gave him a B-.",
  "Indonesia is the world’s largest island nation, but no one knows exactly how many islands it contains (thousands and thousands, to be imprecise). Indonesia attempted to count them all in 2017, but several differing figures still exist.",
  "There are more uncontacted people in Brazil’s portion of the Amazon than anywhere else on the planet, with the number of isolated tribes believed to be more than 100. ",
  "The Yoruba people in Nigeria are known for giving birth to more twins than anywhere else in the world, at a rate of 50 per 1,000 births. The best explanation so far is that Yoruba people eat a type of yam that contains an ovarian stimulate that might release more eggs.",
  "Bangladesh is very warm — so warm, in fact, that the lowest temperature ever recorded was 2.6 degrees Celsius (37.7 degrees Fahrenheit), which is just above freezing. Still, the 2018 cold spell was blamed for 12 deaths. ",
  "In 2012, Russian scientists were able to regenerate a plant from a seed found in Siberian permafrost that was more than 30,000 years old. ",
  "Mexico is home to many pyramids built by the Mayans and other ancient civilizations, but perhaps its least famous triangular structure is actually the largest one in the world. The Aztecs are believed to have built the Great Pyramid of Cholula some 2,000 years ago, and its base is four times larger than Egypt's Great Pyramid of Giza. Today, however, Cholula is mostly covered by dirt and plants.",
  "Located along the earthquake-prone Ring of Fire, Japan experiences 20 percent of the world’s 6.0-magnitude or higher temblors annually. Earthquakes that size can (and do) cause major destruction.",
  "Ethiopia was the site of an archaeological discovery that rewrote human history. In 1974, a 3.2 billion-year-old hominin (early human) fossil was found by paleoanthropologist Donald Johanson. It was the most ancient human skeleton ever unearthed, and helped scientists understand early human behavior. The fossil was named Lucy after the Beatles song “Lucy in the Sky With Diamonds,” which Johanson was listening to the night of the discovery.",
  "About a quarter of all overseas nurses come from the Philippines, making it the world’s top supplier of nurses.",
  "Bread was invented in Egypt around 8,000 BC. (Thanks, Egypt!) The first examples of it were flat and unleavened, most closely resembling what we know today as chapatis in India or tortillas in Latin America. ",
  "Located in VIetnam, one of the top attractions in Hanoi is the Ho Chi Minh Mausoleum. Here you can view the embalmed body of the country’s most beloved leader, known as Uncle Ho, who was encased in glass (against his will). ",
  "Belgium colonized Democratic Republic of Congo from 1908 to 1960, and one of the leftovers from this period is an obsession with mayonnaise. They apparently put it on everything here.",
  "Everyone who lives in Germany, even foreigners, can attend college tuition-free. ",
  "Turkey is known for its delicious desserts like baklava, but it also has a pudding called tavuk gogsu that’s made from, among other things, milk, sugar, cinnamon and shredded chicken breasts. ",
  "Iran is more committed to family planning than any other country on the planet. Religious edicts called fatwas encourage contraceptives, and both men and women are required by law to take a class on modern contraception before their marriage license will be issued. ",
  "There’s an annual festival in Thailand that pays homage to its many monkeys. During the Monkey Buffet Festival, residents of Lopburi provide 4.5 tons of fruits, veggies and candies to the 3,000 monkeys that live around the ancient temple of Phra Prang Sam Yot.",
  "Tea is big on this European island nation (United Kingdom) — locals reportedly drink 165 million cups a day. But it was a Portugeuse woman who first brought the drink to the isles. After Catherine of Braganza wed King Charles II in 1662, her favorite libation, tea from China, quickly caught on in the royal palace, then the rest of the country. ",
  "France is the most visited country in the world with 89 million annual tourists.",
  "One of the most iconic foods in Italy is the tomato. But Italians have only been eating this fruit since the 1500s, when Spanish conquistadors brought it from Peru to Naples, which at the time was under Spanish rule. ",
  "There is a street in the city of Soweto, South Africa called Vilakazi Street that was once home to two very famous South Africans: Nelson Mandela and Desmond Tutu. Both won Nobel peace prizes. ",
  "Rock music legend Freddie Mercury of the band `Queen` was born Farrokh Bulsara in Zanzibar, Tanzania, while it was a British protectorate. The East African island is now part of Tanzania. ",
  "Myanmar is one of only three in the world, along with Liberia and the United States, that does not use the metric system.",
  "The Kalenjin tribe in Kenya produces the world’s best long-distance runners. In one Berlin marathon a few years ago, male runners from this single tribe placed first, second, third, fourth and fifth; women runners from the tribe nabbed first, second and fourth place.",
  "Kimchi and rice are the two most important foodstuffs of South Korea , and there is a common saying that “if you have kimchi and rice then you have a meal.” This reliance on kimchi and rice dates back up to 3,000 years. ",
  "Caño Cristales, a river in Colombia country, is referred to as the “liquid rainbow” because of its many vivid colors, which are produced from the reproductive process of aquatic plants. ",
  "Spain is the birthplace of Miguel de Cervantes, whose iconic “Don Quixote” is considered the first modern novel. The first part was published in 1605 and the second 10 years later. He published several other works but made almost no money off any of them. ",
  "Argentine Diego Maradona is one of the best soccer players of all time. He is so popular in his home country that some 120,000 people worship at the Church of Maradona. Their version of the Lord’s Prayer? Our Diego/Who art on earth/Hallowed be thy left foot/Thy magic come,/Thy goals be remembered.",
  "Uganda is a birder’s paradise. With more than 1,000 species, it contains 60 percent of Africa’s birds and 11 percent of the world’s avian population.  ",
  "Ukraine is one of only 26 countries in the world with a 100 percent literacy rate among adults.",
  "Nobel laureate and famous existentialist Albert Camus was born in Algeria to French parents and began his career in the North African country. ",
  "The ancient Sumerians of Mesopotamia — what is now modern-day Iraq — invented the world’s first writing system, called cuneiform, from 3500-3000 BC. ",
  "Dukhan is a Sudanese tradition that involves a month-long series of smoke baths for brides-to-be that are intended to make their skin smooth and glowing for their wedding day. It’s also used generally by women as a sexual enhancer. ",
  "Dukhan is a Sudanese tradition that involves a month-long series of smoke baths for brides-to-be that are intended to make their skin smooth and glowing for their wedding day. It’s also used generally by women as a sexual enhancer. ",
  "The national sport of Afghanistan is called buzkashi and involves men on horses fighting over half of a calf carcass (goat carcasses were once used, but couldn’t handle the pounding as well). It can get quite violent. ",
  "The humble but delicious bagel was invented Poland. It’s not known exactly when, but it appears to date to at least 1610 and possibly as far back as the 1300s. (Thanks, Poland!)",
  "The 49th parallel marks the border between Canada and the United States. At 5,525 miles, it’s the world’s longest unprotected border.",
  "Dating back to 859, the University of Al-Karaouine in the ancient city of Fes el-Bali is the oldest known university in the world.",
  "Mecca in Saudi Arabia, the holiest Islamic city, is located in this Middle East country. All Muslims are encouraged to visit it at least once, and because of its holy status, only Muslims are allowed to enter. ",
  "Uzbek people have several superstitions surrounding bread, which is considered sacred in this former Soviet republic. These include not placing bread upside down, as that’s considered rude, and breaking off a chunk of bread when leaving home, so it’s preserved when you come back.",
  "Far south from the capital of Lima in Peru are the mysterious Nazca Lines. Dating back to between 500 BC and 500 AD, they are one of archaeology’s great enigmas due to their size, quantity and continuity, and they are only visible from high above. ",
  "The geoglyphs comprise humans figures, plants and animals and are believed to have astronomical significance. ",
  "Sarawak Chamber on the island of Borneo, Malaysia is the largest known cave chamber on Earth. At 2,000 feet long, 1,400 feet wide and almost 500 feet tall, it is twice the size of Britain’s Wembley Stadium.",
  "The wildly popular Brazilian dance style known as samba is rooted in Angolan circle dances.",
  "Kwame Nkrumah, who led Ghana's independence from Britain in 1957, is known as the Father of Pan-Africanism, which sought to unite all people of African descent to create a politically independent continent.  ",
  "Bob Dylan, known for his politically charged songwriting, released an album in 1976 around the time of Mozambique's independence from Portugal that contained a romantic love song called “Mozambique” celebrating the country. It’s unclear why Dylan composed the song, as he’d never visited the country, and the timing of its release was roundly criticized.",
  "Shibam is a 16th-century walled city in Yemen that’s known as the “Manhattan of the Desert” thanks to its impressive mud-brick highrises and grid layout. ",
  "Nepal has no independence day because, unlike most countries around the world, it was never fully occupied by Europeans. It ceded 30 percent of its land to Britain following the Anglo-Nepalese War from 1814-16, but the Brits were never able to conquer it all due to the country’s treacherous terrain. ",
  "Residents of Venezuala cannot legally watch “The Simpsons” because their former president, Hugo Chavez, deemed it unsuitable for children. Confoundingly, it was replaced by “Baywatch.” ",
  "A traditional martial art called Moraingy was developed in Madagascar in the precolonial 17th century and remains wildly popular. It involves bare-knuckle fighting and is comparable to mixed martial arts. ",
  "Often called Africa in miniature, Cameroon touts 1,738 different linguistic groups and more than 200 national languages. ",
  "Ivory Coast is home to the largest church in the world, Basilica of Our Lady of Peace. Completed in 1989, it measures 518 feet tall and covers an area of 323,000 square feet.",
  "Both men and women in Noth Koria can only choose between 15 state-approved haircuts. Punishment ranges from small fines to imprisonment. ",
  "Australia is home to Uluru, or Ayers Rock, a massive red sandstone formation in the Northern Territory that is sacred ground for aboriginals. For years, people have been taking and then returning chunks of sandstone, fearing that the pilfering cursed them with bad luck.",
  "The largest petroglyph in the world can be found in Niger. It depicts two giraffes, with the tallest one measuring nearly 18 feet. It was created 6,000 to 8,000 years ago. ",
  "There’s a sacred fig tree in Sri Lanka that was planted from a cutting some 2,300 years ago and has been lovingly tended to ever since. The cutting was taken from the Indian tree that gave Siddhartha Gautama the enlightenment to become Buddha.",
  "Burkinabé revolutionary Thomas Sankara of Burkina Faso is known as the “African Che Guevara” for his efforts, as president from 1983-87, to rid the country of corruption and environmental degradation while empowering women and boosting education and health-care access. He was assassinated in 1987. ",
  "In the town of Gao in Mali, one can straddle the prime meridian and have one foot in the Western Hemisphere and the other in the Eastern Hemisphere. ",
  "The man who invented the steam espresso machine and the Illycaffe brand, Francesco Illy, was born in Romania in 1892. ",
  "Chile has only volunteer firefighters who are entirely unpaid. In 2014, a massive fire in Valparaiso sparked debate about whether this arrangement should change.",
  "Lake Malawi is vitally important to this country. It is the third-largest lake in Africa, but contains more species of fish — over 1,000 — than any lake in the world.",
  "Ancient Kazakhs are credited with domesticating wild horses. They were able to tame, ride and milk horses some 5,500 years ago. ",
  "The first early human fossil ever discovered in Africa was discovered in the caves of Kabwe in 1921 in Zambia. The fossil’s age? Between 300,000 and 125,000 years old.",
  "Guatemala is the birthplace of chocolate, with ancient Mayans worshipping the cacao tree. (Thanks, Guatemala!)",
  "Mount Chimborazo in Ecuador is not the tallest mountain in the world, but it is the highest spot on Earth and thus closest to outer space. This is because the Earth is not perfectly spherical, but rather oblate. ",
  "Once considered some of the shortest people in the world, the Dutch are now the tallest. Men average just over 6 feet while women average 5 feet 6 inches. ",
  "Mount Qasioun in Syria, which overlooks the capital of Damascus in this Middle East country, is said to be where Cain killed Abel with a rock before carrying his body on his shoulders for centuries.",
  "In 2015, airborne laser scanners found vast ancient cities buried under the jungle near Angkor Wat Cambodia. They were so extensive that by their peak in the 12th century, they would’ve made up the largest empire on Earth. ",
  "On Sundays in Senegal, the waters of the Atlantic Ocean are reserved for sheep bathing. Sheep are a prized animal in the Muslim nation and are therefore very well taken care of.",
  "Chad has one television station, Tele-Tchad, and it’s run by the state. ",
  "Camels are extremely important to the people of Somalia. Of the 14 million camels in the world, more than half reside in Somalia. ",
  "The Victoria Falls waterfall in Zimbabwe is so massive that the sound of water crashing down can be heard 25 miles away, and the spray and mist can be seen from 31 miles away.",
  "Thanks to a long monsoon season, Gunea’s capital, Conkary, is the wettest capital on Earth. It gets about 15 inches of rain a year, compared to the global average of 3.8 inches.",
  "In an effort to improve cleanliness and hygiene,Rwanda has banned things like wearing sandals or going barefoot in public, and people aren’t allowed to share straws. ",
  "Snakes are revered in Benin, so much so that they are welcomed into people’s homes to eat and there’s a building called the Temple of Pythons that houses 50 royal pythons that tourists can visit.",
  "When “Raiders of the Lost Ark” filmed in Tunisia part of the city of Kairouan stood in for 1930s Cairo. An entire day of shooting was lost so 350 TV antennas could be removed from atop buildings near a filming location.",
  "Chocolate is huge in Belgium, which can produce some 600,000 tons of it per year across its more than 2,000 companies and shops specializing in the confection. More chocolate is sold at the Brussels airport than anywhere else in Belgium.",
  "Agriculture is so important to Burundi that 90 percent of the population depends on jobs in this sector to make a living. ",
  "Although the vast majority of Bolivians are Catholic, they still hold many indigenous beliefs, such as sacrificing llamas to the goddess of the Earth, Pachamama. ",
  "The biggest source of revenue in Cuba is not tobacco, sugar, rum or tourism — it’s doctors. The country’s 50,000 doctors working abroad bring Cuba some $11 billion annually. ",
  "The Haitian Revolution, which lasted from 1791 to 1804, ultimately led to the creation of Haiti, making it the first country to be founded by former slaves. ",
  "South Sudan is the youngest country in the world, having achieved full independence in 2011. ",
  "Since being introduced in the 1880s, baseball has been an obsession in Dominican Republic. Today, it has the most foreign-born players in Major League Baseball, at 102. ",
  "Built in 1410, the world’s oldest astronomical clock still in operation resides in Prague, the capital of Czech Republic. ",
  "In order to avoid excessive wear and tear to its historic monuments, Greece banned high heels at archaeological sites. ",
  "There’s a small fishing village called Nazare north of Lisbon (Portugal) where the world’s largest rideable waves occur. It’s believed the biggest-ever wave was 100 feet high.",
  "Folklore and superstition reign supreme in Azerbaijan. Beliefs include not lending money or bread at night and never hurrying off to a funeral.  ",
  "Sweden has not fought in a war in more than 200 years. It sat out both World Wars and its last conflict was in 1814 with neighbor Norway, which had declared its independence.",
  "If you’ve ever dreamed of walking up to an ATM and withdrawing a gold bar, then head to Dubai in UAE, where you can find just such a machine.",
  "For decades, residents of Comayagua inHonduras nation have celebrated Good Friday by creating ornate and colorful sawdust carpets in front of their homes that depict scenes from Jesus Christ’s life. These stunning creations take months of preparation, but inevitably they are trampled on by the celebration’s procession. ",
  "The Rubik’s Cube was invented in Hungary by an architect who named it after himself. Erno Rubik never intended his creation to be a toy but rather a vehicle for helping to understand three-dimensional geometry. ",
  "The Soviet era never really ended in Belarus, and Belarus is often called Europe’s last dictatorship. The secret police are referred to as the KGB and communal farming is still practiced. President Alexander Lukashenko has been in office since the post was created in 1994, and he has staunchly retained the feel of the USSR. ",
  "Tajikistan contains the largest glacier outside of either the north or south poles. Fedchenko Glacier stretches some 47 miles and is located among thousands more glaciers in the Pamir Mountains.",
  "The world’s first zoo, founded in 1752, is still in operation in Austria.",
  "There’s a tribe in New Guinea that still uses shells as its currency. Tabu is the money of choice by the Tolai society, and while it’s not easy to make, it’s used like regular currency. ",
  "Serbia was once the center of the Roman empire and it shows — there were 18 emperors born in what is now modern-day Serbia. The most famous of these was Constantine I, who founded Constantinople (Istanbul) and elevated Christianity to a state-level religion. ",
  "Everyone associates Switzerland with chocolate, and for good reason. Much of chocolate as we know it today was created in Switzerland, including milk chocolate, chocolate with hazelnuts and melting chocolate. ",
  "Israel has a bright history with the tomato. Israel invented the modern cherry tomato, along with a variety that doesn’t drip, one that’s resistant to viruses and another that doesn’t spoil even after a week on the counter. ",
  "About one-third of the population in Togo adhere to an ancestral form of belief, including voodoo. In Lome, Togo’s capital, merchants sell voodoo talismans known as “fetishes.”",
  "English is the official language in Sierra Leone, but everyone also speaks Krio — an English-based creole language — so the various ethnic groups can communicate with one another. ",
  "During the Secret War from 1964-73, U.S. forces dropped over 2 million tons of ordnance in Laos. That’s equivalent to a planeload of bombs every 8 minutes daily for nine years, making Laos the most heavily bombed country per capita in world history. ",
  "Paraguay unfortunately has a history with German Aryans dating back to the 1880s, when Bernhard Förster, the father of Nazism, relocated to Paraguay. Before and during World War II, the country backed Germany. Then after the war, Paraguay became a Nazi hideaway. ",
  "Bulgaria claims to have accidentally created yogurt some 4,000 years ago. Either way, the main fermentation bacteria in the creamy dairy product is named after Bulgaria, lactobacillus bulgaricus, and was first discovered in the region. ",
  "t’s believed that Jesus Christ’s famous miracle of turning water into wine took place in Qana, a village in the southern part of Lebanon. ",
  "Oil explorations in the 1950s uncovered a “fossil” aquifer in Libya that is 40,000 years old and existed before the end of the last ice age. ",
  "The sky is so clear at night in Nicaragua that stargazers can see 86 of the 88 constellations. ",
  "El-Savador is the only country in Central America that doesn’t have a coastline on the Caribbean Sea.  ",
  "At 20 times longer than the “Odyssey” by Homer, the “Epic of Manas” is considered the longest poem in the world. It was written by many people starting in the 1800s and finishing with the first publication in the 1920s. Manas is a folk hero in Kyrgyzstan. ",
  "Melons are so important to the culture and history of Turkmenistan that it has a holiday dedicated to the fruit that takes place each August. ",
  "An island city-state in Southeast Asia, Singapore printed its entire national anthem in microtext on the back of a $1,000 note. ",
  "Bicycles are much more prevalent than personal automobiles in Denmark. Only four out of 10 Danes own a vehicle, while nine out of 10 own a bike. ",
  "The baby box has been a Finnish institution since the 1930s, when Finland’s infant mortality rate was high. Since 1949, the Finnish government has given every expectant mother a cardboard box that their baby can sleep in, filled with essential items like clothes, sheets and toys.",
  "Bratislava, the capital of Slovakia, is the only capital in the world that borders two other countries, Austria and Hungary.",
  "Not to be confused with its much larger neighbor, the Democratic Republic of Congo, Republic of Congo is home to what a “National Geographic” team dubbed “the world’s last eden” during a visit in the 1990s. They were in Parc National Nouabalé-Ndoki, a swampy forested region teeming with flora and fauna. ",
  "In the 1980s, Norway started selling salmon, one of its major exports, to Japan because that island nation was facing a seafood shortage. The Norwegians even suggested using it in sushi and sashimi. Though the Japanese were hesitant at first, it became a raw-seafood staple for them by 1995.",
  "Due to its location 8 to 12 degrees north of the equator, Costa Rica is always about the same distance from the sun. That means it has 12 hours of light and 12 hours of night every day of the year, and sunrise and sunset times are always within a one-hour period. ",
  "Palestine, located between Jordan and Israel contains a small city called Bethlehem that, in addition to being the birthplace of Jesus Christ, celebrates Christmas three times a year: Jan. 7 (Greek Orthodox), Jan. 18 (Armenians) and Dec. 25 (Catholics).",
  "In Oman, there is a women-only souk (Arab bazaar) held every Wednesday in a small city called Ibra. On that day, men are not allowed to visit the souk or sell anything there.  ",
  "The American Colonization Society founded Liberia in the early 1800s as a place where free-born black Americans and freed slaves could live. In the first few years of its existence, nearly 20,000 people relocated there. ",
  "Guinness is arguably Ireland's most recognizable beverage. When Arthur Guinness signed the lease for the brewery’s St. James Gate property in 1759, it was for 9,000 years at £45 per month. Those terms are still adhered to today.",
  "In 1893, New Zealand in Oceania became the first self-governing country in the world to allow women to vote in parliamentary elections. ",
  "Central African Republic in the middle of Africa is one of the three least light-polluted areas in the world, along with Chad and Madagascar.  ",
  "The Richat Structure, an uplifted dome that has eroded away, is located in Mauritania. Often called the Eye of the Sahara, it’s best viewed from space, where it can easily be seen.  ",
  "From the top of Panama’s highest point, Volcan Baru, you can watch the sun rise over the Pacific Ocean and set over the Atlantic Ocean on the same day. ",
  "There is a tire dump in Kuwait that is so massive, it’s not only the biggest in the world, but it can be seen from space. ",
  "Croatia on the Adriatic Sea is credited with inventing the necktie. During France’s 30-year war In the 17th century, King Louis XIII hired Croatian mercenaries who wore a piece of cloth around their necks that the king was particularly fond of. He called it La Cravate, which is still the French term for a necktie. ",
  "The world’s largest wine cellar is buried in Moldovia. The Milestii Mici wine cellar contains nearly 2 million bottles and the tunnel system housing them stretches for 75 miles. Cars and bikes are needed to traverse it, and the same road rules apply underground as above ground. ",
  "“Georgia” is the English name for this Eurasian nation and former Soviet republic, but no one knows exactly how it gained this moniker because the natives call their country Sakartvelo. There are many ideas, including that because of their reverence for St. George, outsiders bestowed that name on the area. ",
  "Eritrea in North Africa gained independence from Ethiopia in 1993 after a 30-year war, yet it has not held an election since. Its constitution was suspended in 1997 and there is only one political party in the entire country, the People’s Front for Democracy and Justice.",
  "At nearly 6 minutes long, Uruguay has the world’s longest national anthem. The lyrics were composed in 1833 — by the same man who wrote Paraguay’s anthem — and the music was added in 1848. ",
  "Thanks to the work of an amateur archaeologist in the early 2000s, residents and government officials in Bosnia and Herzegovina in southeast Europe believe that a network of 12,000-year-old pyramids exists within the country’s borders. That would make them far older than the Egyptian pyramids, and Bosnia would be the cradle of European civilization.",
  "The national drink of this Mongolia, called airag, is made of fermented milk from horses, which are a revered animal in Mongolia. The milk is fermented over a few days, traditionally in a leather sack that hangs outside one’s yurt, and contains about 2 percent alcohol.",
  "The game of chess is huge in this Armenia located between Europe and Asia. Armenia is the only country in the world that requires students to take chess lessons in school, and it’s paid off — the country often wins international competitions and has a high number of grandmasters per capita.",
  "Jamaica has no snow or winter-like conditions at any time of the year, but it does have what’s arguably the world’s most famous bobsled team. It first competed in the Olympics in 1988. ",
  "Mother Teresa was ethnically Albanian and remains the only person from this European country to have won the Nobel Prize.",
  "In terms of the likelihood of a natural disaster, Qatar is the safest country in the world.",
  "Lithuania was the largest country in Europe in the 15th century. Called the Grand Duchy of Lithuania, it included what’s now Belarus and parts of Ukraine, Poland and Russia.",
  "The Namib Desert, from which Namibia gets its name, is the oldest desert in the world at 55 million years old. ",
  "Only recently did Gambia switch from marbles to paper ballots for elections. The marbles practice started in the 1960s as a way to avoid spoiled ballots and to make it easier for illiterate citizens to vote. ",
  "Botswana in Southern Africa has the continent’s highest concentration of elephants thanks to strict regulations around hunting.",
  "Some 80 percent of Africa’s gorilla population reside in Gabon. ",
  "Lesotho has the special distinction of being the “highest lowest point” in the world — it’s the only country that’s located entirely above 1,000 meters, or about 3,280 feet",
  "Another former Yugoslavian republic, North Macedonia is the birthplace of the Cyrillic alphabet, which is used in more than 50 languages. It was created by brothers Saints Cyril and Methodius in the 9th century. ",
  "Bees are big in this former Yugoslavian republic. Of the 2 million residents of Slovenia, some 90,000 are beekeepers — that’s 1 out of every 20 people!",
  "The rising global demand for cashews has been a boon for Buinea-Bissau. The crop accounts for 80 percent of the country’s export revenue. ",
  "The first time a conifer was decorated for Christmas in the style we know today was in 1510 in Riga, Latvia.",
  "Unlike in many of its Middle East neighbors, women are allowed to vote and run for office in Bahrain. ",
  "The Limbo dance originated in the 1950s on this twin-island nation (Trinidad and Tobago) just north of Venezuela. It was originally performed at funerals and is meant to reflect the cycle of life.",
  "Spain has twice occupied Equitorial Guinea, and it’s the only country on the continent with Spanish as its official language.",
  "Estonia is considered the most digitally advanced government in the world and was the first to offer its citizens online voting, all the way back in 2005. ",
  "After Portugal withdrew from East Timor nation in 1975 after centuries of occupation, Indonesia invaded and held the country until 1999. In 2002, East Timor became the first new country of the 21st century. ",
  "The only known habitat of the dodo bird — it of human-induced extinction fame (“don’t go the way of the dodo…”) — was on Mauritius, although the cause of its demise is debatable. ",
  "The Greek goddess of love, Aphrodite, is said to have been born on a beach Cypru's Mediterranean Sea. ",
  "Known as Swaziland until 2018, Eswatini is one of the world’s last absolute monarchies. And King Mswati is permitted to take another wife every year if he so chooses; his predecessor, for instance, had 125 wives. ",
  "Djibouti in southern Africa once had a national soccer team, but it was dissolved in 2017 because of continued poor results. It had never qualified for any major international tournament. ",
  "Firewalking on hot stones is an ancient tradition that started in Fiji. It’s even believed that descendants of the first man to do so can still walk on white-hot stones. ",
  "Comoros, in the Indian Ocean is one of the world’s most politically unstable countries, with a coup d’etat or an attempt at one happening every two years or so since 1975.",
  "Guyana has the unfortunate distinction of being the site of the world’s largest mass suicide. On Nov. 18, 1978, more than 900 men, women and children living in Jim Jones’s Peoples Temple drank poison-laced Kool Aid and died.",
  "Tourists to Bhutan have to pay a minimum of $200 per day (in the low season) to visit the country. While that sounds excessive, it’s basically all-inclusive — food, transportation, accommodations, daily guide and local taxes.",
  "Some 5 to 10 percent of Solomon Islands' population of this Oceania island nation have blond hair. The gene that causes this is naturally occurring and totally distinct from the one that gives Europeans blond hair.",
  "Montenegro in southeastern Europe is home to what’s considered one of, if not the, world’s oldest olive tree: Stara Maslina. It’s more than 2,000 years old and lives among several other olive trees that are 500 to 700 years old.",
  "There is a dancing ceremony in Luxemburg that is so old and so popular that in 2010 it was included on UNESCO’s Intangible Cultural Heritage of Humanity list. It involves some 10,000 people simultaneously hopping while another 40,000 look on. ",
  "Located on the northeast coast of South America, Suriname has only one movie theater, in the capital city of Paramaribo.",
  "Due to repeated droughts in the 20th century, many Cabo Verdeans left the West African island nation for better opportunities. Because of this widespread emigration, the expat population is now greater than the domestic population. ",
  "The U.S. Defense Department’s Operation Christmas Drop started in 1952 on one of the many islands that make up Micronesia in the North Pacific Ocean. It’s the longest-running humanitarian effort by the Defense Department and now includes over 50 islands in the Pacifi",
  "In 2009, the government of Maldives off the southern coast of India held the world’s first and only cabinet meeting underwater to highlight the impending doom of climate change. It was part stunt and part cry for help, and it at least succeeded in attracting media attention.",
  "One of Malta’s islands, Gozo, has a cave that is apparently featured in Homer’s “Odyssey.” Gozo serves as the Island of Ogygia in the epic poem and the cave in question is where Calypso the nymph held Odysseus as her prisoner of love for seven years.",
  "Brunei is one of the only countries in the world governed by an absolute monarchy. Hassanal Bolkiah has served as Brunei’s Sultan since 1967, making him the second-longest serving monarch in the world after Queen Elizabeth II of Great Britain. ",
  "Would you believe there’s a country where a rat-like creature is considered a culinary delicacy? It’s true, and it’s in Belize. Gibnut is so revered in these parts that it was served to Queen Elizabeth II in 1985 during a royal visit. ",
  "Just north of the Caribbean Sea and just east of Florida lies the chain of hundreds of islands that make up the Bahamas. And although the country is located along the Tropic of Cancer, it has snowed once in recorded history. The bitterly cold winter of 1977 made its way to the Bahamas and on January 19, snow fell on Grand Bahama Island",
  "Iceland is known for being tops in a lot of per-capita categories, but none is more surprising than Coca-Cola. Icelanders, per capita, consume more of the soft drink than any other country in the world.  ",
  "Vanuatu is famous for something called “land diving” that inspired bungee jumping. Men fasten plant vines to their ankles and jump off a rickety wooden platform high above the ground. The courage of these jumps, according to religious symbolism, is directly tied to the success of the year’s yam harvest. ",
  "Mongooses are a familiar sight on Barbados island. The were first brought from India in the 1870s to quell the rat population, but that effort failed. Now they are simply part of the island. ",
  "Relationships are a bit different in Sao Tome than most other places in the world. Traditional Christian marriage is largely reserved for the upper class, and it’s acceptable for men to maintain several households. Co-residential living is also popular, and men and women both have multiple partners and children with different people over the course of their lives. ",
  "Samoa, an island nation in the South Pacific Ocean, has a third gender called fa'afafines. The practice dates to before colonization and is quite progressive compared to the rest of the world. Samoans realize everyone is different, and if a boy displays effeminate behavior in childhood he is encouraged to embrace those tendencies and is fully accepted by society. ",
  "St Lucia in the Caribbean Sea is the only country in the world that’s named after a woman, in this case Saint Lucy of Syracuse. French settlers were the first Europeans to arrive on the island, and gave it that name. ",
  "Due to its placement in the central Pacific Ocean and the fact that its islands cover an area of 1.3 million square miles, Kiribati has the special distinction of being the only country in the world that’s located in all four hemispheres. ",
  "Until the early 1800s, nutmeg production was entirely centered in Indonesia. But during the Napoleonic wars, the British transplanted nutmeg trees to many other locales, including Grenada in the Caribbean. Now, Grenada for 40 percent of the world’s nutmeg production.",
  "The Western Hemisphere’s oldest botanical garden is located within Saint Vincent and Grenadines. Established in 1765, the gardens contain native flora and breadfruit trees first brought to the island from Tahiti. ",
  "Bats thrive on many of the dozens of islands that make up Tonga because they are considered sacred and the official property of the ruling monarchy, who are the only ones who can touch the flying critters. ",
  "French pirate Olivier Levasseur is rumored to have buried tens of millions of dollars worth of treasure on Mahe, one of the islands that make up Seychelles. Since 1950, a father and son have been trying to find the loot. ",
  "Cricket is incredibly popular among residents of Antigua and Barbuda islands, a holdover from Britain’s colonial rule. And although the nation’s population is low, it has produced several of the greatest cricket players of all time, including Viv Richards, Richie Richardson, Andy Roberts and Curtly Ambrose. ",
  "Straddling the border of France and Spain is the miniscule nation of Andorra, which in its 1,000-year history has never engaged in battle. However, during World War I, it was one of the first countries to declare war with Germany despite the fact that it had no military. And since its demands were ignored in the Treaty of Versailles, it remained “at war” with Germany until the outbreak of World War II in 1939.  ",
  "There is an opening called a fumarole on one of Dominica Islands  numerous volcanoes that shoots hot sulphuric gas into a 200-foot wide body of water, creating the world’s second-largest natural hot spring. It’s fittingly called Boiling Lake and is only accessible via a four-hour hike. ",
  "In 2011, this Pacific Ocean nation comprised of dozens of islands and atolls created the largest shark sanctuary in the world. By adding 772,000 square miles of space, the Marshall Islands nearly doubled the amount of protected ocean for the marine mammals. ",
  "Christopher Columbus named Saint Kitts and Nevis islands after himself (“Kitts” was the famous explorer’s nickname) and the Spanish word for snow (“nieves”), even though snow is the last thing you’d ever find in a place with an average annual temperature of 82 degrees. ",
  "One of the things Monaco, a tiny country surrounded by France and the Mediterranean Sea, is most known for is its casino in Monte Carlo, but local residents of the country are barred from entering it unless they work there. The laws date to the introduction of gambling in the country in the mid-1800s to save the nation from bankruptcy. Monaco wanted foreign money from this pursuit, but it didn’t want its own citizens going into debt from gambling addictions.  ",
  "Liechtenstein, sandwiched between Austria and Switzerland is the world’s top producer of false teeth. Ivoclar Vivadent manufactures 60 million artificial teeth annually, which is 20 percent of all false teeth made worldwide. ",
  "Landlocked inside Italy, San Marino is an ancient and tiny country with one very famous honorary citizen: Abraham Lincoln. In 1861, Lincoln had just been sworn in as the 16th U.S. president and was receiving congratulatory letters from around the world. But the one that piqued his interest the most was from the world’s oldest republic, San Marino, wishing the U.S. well as the Civil War loomed and Lincoln tried to keep the peace. ",
  "Located east of the Philippines, Palau is a small island nation and one of the only places in the world that adheres to a strict matrilineal system in which kinship is traced through the mother’s family line. Women choose male chiefs and have the power to rescind that status. They keep the money, and the mother’s brother is tasked with providing for her children. ",
  "A collection of islands halfway between Hawaii and Australia, Tuvalu’s largest source of income is derived from its country code domain, .tv. The country has had several agreements in place since the late 1990s with companies that sell web addresses using the desirable suffix. ",
  "This 8-square-mile island nation (Nauru) in the South Pacific Ocean does rank first in something, although it would probably rather not be the fattest country in the world with a mean body-mass index of 32.5 and 61 percent of its residents considered obese.",
  "Holy See, The smallest recognized independent country in the world uses the euro as its currency even though it’s not part of the Eurozone or European Union. And like other countries, it mints its own euro coins and issues its own stamps. it has a population of only about 900 people!",
  "There’s a small city called Sialkot in Pakistan that produces 40 percent of the world’s soccer balls.",
];

export const photos = [
  "https://images.pexels.com/photos/6346796/pexels-photo-6346796.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.pexels.com/photos/10318064/pexels-photo-10318064.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.pexels.com/photos/7425352/pexels-photo-7425352.jpeg?cs=srgb&dl=pexels-nothing-ahead-7425352.jpg&fm=jpg",
  "https://images.pexels.com/photos/10235901/pexels-photo-10235901.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.pexels.com/photos/4397890/pexels-photo-4397890.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.pexels.com/photos/2660262/pexels-photo-2660262.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.unsplash.com/photo-1463592177119-bab2a00f3ccb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80",
  "https://images.unsplash.com/photo-1472739841375-d0ea9f0cb6a6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=388&q=80",
  "https://images.unsplash.com/photo-1568675392503-1cf97bb81c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  "https://images.pexels.com/photos/1400249/pexels-photo-1400249.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.pexels.com/photos/3761529/pexels-photo-3761529.jpeg?cs=srgb&dl=pexels-tushar-3761529.jpg&fm=jpg",
  "https://images.pexels.com/photos/3879160/pexels-photo-3879160.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
  "https://images.unsplash.com/photo-1510736769521-207ed84f191e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=315&q=80",
  "https://images.unsplash.com/photo-1622207691293-5cd80466dab3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  "https://images.unsplash.com/photo-1600362114812-caa0d6d1b97c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  "https://images.unsplash.com/photo-1532336414038-cf19250c5757?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  "https://images.unsplash.com/photo-1571139317861-76cd3c032c76?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  "https://images.unsplash.com/photo-1425543033754-7d8f86ea397d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  "https://images.unsplash.com/photo-1599819548353-2c32ed28cd6d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=386&q=80",
  "https://images.unsplash.com/photo-1473167052083-3d31fa1f6776?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=437&q=80",
  "https://images.pexels.com/photos/6580703/pexels-photo-6580703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.unsplash.com/photo-1621183038095-871fba739987?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  "https://images.unsplash.com/photo-1592326871020-04f58c1a52f3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=465&q=80",
  "https://images.pexels.com/photos/4314682/pexels-photo-4314682.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.pexels.com/photos/2102632/pexels-photo-2102632.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.pexels.com/photos/3540318/pexels-photo-3540318.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.pexels.com/photos/3889908/pexels-photo-3889908.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.pexels.com/photos/6536034/pexels-photo-6536034.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.pexels.com/photos/2880801/pexels-photo-2880801.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.pexels.com/photos/2070485/pexels-photo-2070485.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
  "https://images.pexels.com/photos/3421920/pexels-photo-3421920.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
  "https://images.pexels.com/photos/5500779/pexels-photo-5500779.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.pexels.com/photos/4558351/pexels-photo-4558351.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.pexels.com/photos/52526/sign-places-travel-information-52526.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "https://images.pexels.com/photos/4652131/pexels-photo-4652131.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
];
